name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: build
        run: |
          pip install build; python -m build --sdist
          # test whether tarball contains all files required for compiling
          pip install dist/cydifflib-*.tar.gz

      - name: Test with pytest
        run: |
          pytest tests
